### ISSUE TITLE
trip-simulator lib API

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/trip-simulator#24]
I would like to break out the path simulation code into a library API called by the CLI. This will allow for tests around core functions, as well as the ability to use the GPS physical simulation functionality in custom use cases, such as creating paths from a pre-existing OD pair dataset.

**Comment by eth4io** [comment]
HI Morgan, would like to help with this, especially for creating paths from a pre-existing OD pair part.
Where would you recommend to start with?

**Comment by morganherlocker** [comment]
@eth4io Good question, I've been trying to think about a reasonable architecture here. In v1, this tool was designed to work with a pre-existing OD pair dataset. The new implementation in v2 works a bit differently and progressively builds trips as the simulation ticks forward. Additionally, we moved to a model that simulates the activity between trips as well, as driver agents search for a new passenger. Maybe we could generate a new driver as the simulation ticks past each trip, then delete the agent as their trips end?

**Comment by eth4io** [comment]
Dismissing agents with some probability and generating new agents would be good idea as in reality not all drivers drives all day and some may also just do few trips. They can also have preferred start and end point as drivers most likely start / end at somewhere near home

**Comment by morganherlocker** [comment]
I've decided against implementing this. v2 and v3 really settled on a form factor that feels clunky in a library format, and I don't see this changing in v4.
