### ISSUE TITLE
[question] Is frequency param used at all?

### ISSUE THREAD

**Issue by kuanb** [sharedstreets/trip-simulator#34]
In each config, an attribute `frequency` is set, but does not appear to be used elsewhere in the code:
https://github.com/sharedstreets/trip-simulator/blob/a1497e6b371b4bdd9c18eef59ce09f38b62a53d5/configs/bike.json#L4

Is this an unused attribute or, if it is used, how/where?

**Comment by morganherlocker** [comment]
It is not currently, but I included it with the intent to be able to set each agent's average frequency along a normal distribution, with a second normal distribution along that average, for local variation.

**Comment by kuanb** [comment]
Got it, thanks!
